version: '3'

services:
  database:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: honkai_star_rail
      MYSQL_PASSWORD: test55
      MYSQL_ROOT_PASSWORD: test55
      MYSQL_USER: admin
    volumes:
      - honkai_star_rail:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  honkai_star_rail:
###< doctrine/doctrine-bundle ###
